// flow-typed signature: 7918ba9b4391e79fcf925cd43a0c9ffe
// flow-typed version: <<STUB>>/react-duotone_v^2.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-duotone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-duotone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-duotone/dist/react-duotone' {
  declare module.exports: any;
}

declare module 'react-duotone/dist/react-duotone.min' {
  declare module.exports: any;
}

declare module 'react-duotone/lib/component' {
  declare module.exports: any;
}

declare module 'react-duotone/lib/create-duotone-gradient' {
  declare module.exports: any;
}

declare module 'react-duotone/lib/create-duotone-image' {
  declare module.exports: any;
}

declare module 'react-duotone/lib/hex-to-rgb' {
  declare module.exports: any;
}

declare module 'react-duotone/lib/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-duotone/dist/react-duotone.js' {
  declare module.exports: $Exports<'react-duotone/dist/react-duotone'>;
}
declare module 'react-duotone/dist/react-duotone.min.js' {
  declare module.exports: $Exports<'react-duotone/dist/react-duotone.min'>;
}
declare module 'react-duotone/lib/component.js' {
  declare module.exports: $Exports<'react-duotone/lib/component'>;
}
declare module 'react-duotone/lib/create-duotone-gradient.js' {
  declare module.exports: $Exports<'react-duotone/lib/create-duotone-gradient'>;
}
declare module 'react-duotone/lib/create-duotone-image.js' {
  declare module.exports: $Exports<'react-duotone/lib/create-duotone-image'>;
}
declare module 'react-duotone/lib/hex-to-rgb.js' {
  declare module.exports: $Exports<'react-duotone/lib/hex-to-rgb'>;
}
declare module 'react-duotone/lib/main.js' {
  declare module.exports: $Exports<'react-duotone/lib/main'>;
}
